// carr/src/App.tsx
import { useState, useEffect } from 'react';
import Navigation from './components/Navigation';
import Hero from './components/Hero';
import Features from './components/Features';
import Gallery from './components/Gallery';
import Contact from './components/Contact';
import Login from './components/Login';
import SalesModule from './components/SalesModule';
import OrdersInbox from './components/OrdersInbox';
import VehicleTracking from './components/VehicleTracking';
import { isAuthenticated, getCurrentUser, logout } from './services/authService';

export type ViewType = 'home' | 'sales' | 'orders' | 'tracking';

function App() {
  const [currentView, setCurrentView] = useState<ViewType>('home');
  const [isAuth, setIsAuth] = useState(false);
  const [userEmail, setUserEmail] = useState('');
  const [isLoginOpen, setIsLoginOpen] = useState(false);

  useEffect(() => {
    if (!isAuthenticated()) return;

    getCurrentUser().then((user) => {
      if (user) {
        setIsAuth(true);
        setUserEmail(user.email);
      }
    });
  }, []);

  const handleLoginSuccess = (email: string) => {
    setIsAuth(true);
    setUserEmail(email);
    setIsLoginOpen(false);
  };

  const handleLogout = async () => {
    await logout();
    setIsAuth(false);
    setUserEmail('');
    setCurrentView('home');
  };

  const handleViewChange = (view: ViewType) => {
    if (['sales', 'orders', 'tracking'].includes(view) && !isAuth) {
      setIsLoginOpen(true);
      return;
    }
    setCurrentView(view);
  };

  const renderView = () => {
    switch (currentView) {
      case 'sales':
        return isAuth ? <SalesModule /> : null;
      case 'orders':
        return isAuth ? <OrdersInbox /> : null;
      case 'tracking':
        return isAuth ? <VehicleTracking /> : null;
      default:
        return (
          <>
            <Hero />
            <Features />
            <Gallery />
            <Contact />
          </>
        );
    }
  };

  return (
    <div className="min-h-screen bg-black">
      <Navigation
        currentView={currentView}
        onViewChange={handleViewChange}
        isAuthenticated={isAuth}
        onLogin={() => setIsLoginOpen(true)}
        onLogout={handleLogout}
        userEmail={userEmail}
      />
      {renderView()}
      <Login
        isOpen={isLoginOpen}
        onClose={() => setIsLoginOpen(false)}
        onLoginSuccess={handleLoginSuccess}
      />
    </div>
  );
}

export default App;

// carr-main (2)/carr-main/rely-angular/src/app/app.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';
import { AuthService } from './services/auth.service';
import { ViewType } from './components/navigation/navigation.component';

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
  standalone: false,
  styleUrl: './app.css',
})
export class App implements OnInit, OnDestroy {
  isAuth = false;
  userEmail = '';
  isLoginOpen = false;
  currentView: ViewType = 'home';

  private routerSub?: Subscription;

  constructor(private authService: AuthService, private router: Router) {}

  ngOnInit(): void {
    // Track route changes reactively
    this.routerSub = this.router.events
      .pipe(filter(e => e instanceof NavigationEnd))
      .subscribe((e) => {
        const url = (e as NavigationEnd).urlAfterRedirects;
        if (url.startsWith('/ventas')) this.currentView = 'sales';
        else if (url.startsWith('/ordenes')) this.currentView = 'orders';
        else if (url.startsWith('/tracking')) this.currentView = 'tracking';
        else this.currentView = 'home';
      });

    // Set initial view
    const url = this.router.url;
    if (url.startsWith('/ventas')) this.currentView = 'sales';
    else if (url.startsWith('/ordenes')) this.currentView = 'orders';
    else if (url.startsWith('/tracking')) this.currentView = 'tracking';
    else this.currentView = 'home';

    // Restore session
    if (!this.authService.isAuthenticated()) return;
    this.authService.getCurrentUser().then((user) => {
      if (user) {
        this.isAuth = true;
        this.userEmail = user.email;
      }
    });
  }

  ngOnDestroy(): void {
    this.routerSub?.unsubscribe();
  }

  handleViewChange(view: ViewType): void {
    if (['sales', 'orders', 'tracking'].includes(view) && !this.isAuth) {
      this.isLoginOpen = true;
      return;
    }
    const routes: Record<ViewType, string> = {
      home: '/',
      sales: '/ventas',
      orders: '/ordenes',
      tracking: '/tracking',
    };
    this.router.navigate([routes[view]]);
  }

  handleLoginSuccess(email: string): void {
    this.isAuth = true;
    this.userEmail = email;
    this.isLoginOpen = false;
  }

  async handleLogout(): Promise<void> {
    await this.authService.logout();
    this.isAuth = false;
    this.userEmail = '';
    this.router.navigate(['/']);
  }
}
