// carr-main (2)/carr-main/rely-angular/src/app/components/purchase/purchase.component.ts
import { Component, Input, Output, EventEmitter, OnChanges } from '@angular/core';

interface VehicleData {
  price: number;
  model: string;
  year?: number;
  color: string;
}

interface FormData {
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  reference_number: string;
  paymentMethod: string;
  notes: string;
}

const emptyForm: FormData = {
  first_name: '',
  last_name: '',
  email: '',
  phone: '',
  reference_number: '',
  paymentMethod: 'Transferencia',
  notes: '',
};

@Component({
  standalone: false,
  selector: 'app-purchase',
  templateUrl: './purchase.component.html',
  styleUrls: ['./purchase.component.css'],
})
export class PurchaseComponent {
  @Input() isOpen = false;
  @Input() vehicleData?: VehicleData;
  @Output() closeModal = new EventEmitter<void>();

  formData: FormData = { ...emptyForm };
  isSubmitted = false;
  isLoading = false;
  error = '';

  get currentVehicle(): VehicleData {
    return this.vehicleData || { price: 50000.00, model: 'RELY', year: 2024, color: 'Blanco' };
  }

  handleInputChange(field: keyof FormData, value: string): void {
    this.formData = { ...this.formData, [field]: value };
    this.error = '';
  }

  async handleSubmit(e: Event): Promise<void> {
    e.preventDefault();
    this.error = '';

    const { first_name, last_name, email, phone, reference_number } = this.formData;
    if (!first_name || !last_name || !email || !phone || !reference_number) {
      this.error = 'Por favor completa todos los campos obligatorios';
      return;
    }

    this.isLoading = true;

    const dataToSend = {
      first_name: this.formData.first_name,
      last_name: this.formData.last_name,
      email: this.formData.email,
      phone: this.formData.phone,
      reference_number: this.formData.reference_number,
      price: this.currentVehicle.price,
      vehicleModel: this.currentVehicle.model,
      vehicleYear: this.currentVehicle.year,
      vehicleColor: this.currentVehicle.color,
      paymentMethod: this.formData.paymentMethod,
      notes: this.formData.notes,
    };

    try {
      const response = await fetch('http://localhost:8000/api/ordenes/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('rely_access')}`,
        },
        body: JSON.stringify(dataToSend),
      });

      const result = await response.json();

      if (response.ok) {
        this.isSubmitted = true;
        setTimeout(() => {
          this.closeModal.emit();
          this.formData = { ...emptyForm };
          this.isSubmitted = false;
        }, 4000);
      } else {
        if (result.reference_number) {
          this.error = `Error: ${result.reference_number[0]}`;
        } else if (result.detail) {
          this.error = 'No tienes permiso o tu sesión expiró.';
        } else {
          this.error = 'Hubo un problema al procesar la orden.';
        }
      }
    } catch {
      this.error = 'No se pudo conectar con el servidor de ventas.';
    } finally {
      this.isLoading = false;
    }
  }
}

<div *ngIf="isOpen" class="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4 overflow-y-auto">
  <div class="bg-gray-950 rounded-2xl w-full max-w-md shadow-2xl border border-gray-800 my-8">
    <div class="flex justify-between items-center p-6 border-b border-gray-800">
      <h2 class="text-2xl font-bold text-white">Finalizar Compra</h2>
      <button (click)="closeModal.emit()" class="p-2 hover:bg-gray-800 rounded-lg transition-colors">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#9ca3af" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
      </button>
    </div>

    <div class="p-6">
      <!-- Success state -->
      <div *ngIf="isSubmitted; else formTpl" class="text-center py-8">
        <div class="flex justify-center mb-4">
          <div class="bg-green-500/20 p-4 rounded-full">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#22c55e" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
          </div>
        </div>
        <h3 class="text-xl font-bold text-white mb-2">¡Orden Guardada!</h3>
        <p class="text-gray-400 mb-4">La referencia {{ formData.reference_number }} ha sido registrada en el sistema.</p>
        <p class="text-orange-500 text-sm font-medium">Cerrando ventana...</p>
      </div>

      <!-- Form -->
      <ng-template #formTpl>
        <form (ngSubmit)="handleSubmit($event)" class="space-y-4">
          <!-- Vehicle summary -->
          <div class="bg-gray-900 p-4 rounded-lg border border-gray-800 mb-4">
            <div class="flex justify-between items-end">
              <div>
                <p class="text-gray-400 text-xs uppercase tracking-wider">Vehículo</p>
                <p class="text-xl font-bold text-white">
                  {{ currentVehicle.model }}
                  <span class="text-gray-500 text-sm">{{ currentVehicle.year }}</span>
                </p>
              </div>
              <div class="text-right">
                <p class="text-gray-400 text-xs uppercase tracking-wider">Precio</p>
                <p class="text-2xl font-bold text-orange-500">${{ currentVehicle.price.toLocaleString() }}</p>
              </div>
            </div>
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-xs font-medium text-gray-400 mb-1 uppercase">Nombres</label>
              <input type="text"
                [value]="formData.first_name"
                (input)="handleInputChange('first_name', $any($event.target).value)"
                required
                class="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
            </div>
            <div>
              <label class="block text-xs font-medium text-gray-400 mb-1 uppercase">Apellidos</label>
              <input type="text"
                [value]="formData.last_name"
                (input)="handleInputChange('last_name', $any($event.target).value)"
                required
                class="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
            </div>
          </div>

          <div>
            <label class="block text-xs font-medium text-gray-400 mb-1 uppercase">Email</label>
            <input type="email"
              [value]="formData.email"
              (input)="handleInputChange('email', $any($event.target).value)"
              required
              placeholder="correo@email.com"
              class="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
          </div>

          <div>
            <label class="block text-xs font-medium text-gray-400 mb-1 uppercase">Teléfono</label>
            <input type="tel"
              [value]="formData.phone"
              (input)="handleInputChange('phone', $any($event.target).value)"
              required
              class="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-xs font-medium text-gray-400 mb-1 uppercase">Ref. de Pago</label>
              <input type="text"
                [value]="formData.reference_number"
                (input)="handleInputChange('reference_number', $any($event.target).value)"
                required
                class="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
            </div>
            <div>
              <label class="block text-xs font-medium text-gray-400 mb-1 uppercase">Método</label>
              <select
                [value]="formData.paymentMethod"
                (change)="handleInputChange('paymentMethod', $any($event.target).value)"
                class="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none">
                <option value="Transferencia">Transferencia</option>
                <option value="Zelle">Zelle</option>
                <option value="Efectivo">Efectivo</option>
                <option value="Crypto">Crypto</option>
              </select>
            </div>
          </div>

          <div *ngIf="error" class="bg-red-500/10 border border-red-500/50 text-red-400 p-3 rounded-lg text-xs italic">
            {{ error }}
          </div>

          <div class="pt-4 space-y-3">
            <button type="submit"
              [disabled]="isLoading"
              class="w-full bg-orange-600 text-white py-3 rounded-lg font-bold hover:bg-orange-700 transition-all disabled:opacity-50 flex justify-center items-center gap-2">
              <ng-container *ngIf="isLoading; else submitText">
                <div class="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                Procesando con el Servidor...
              </ng-container>
              <ng-template #submitText>Confirmar y Registrar Venta</ng-template>
            </button>
          </div>
        </form>
      </ng-template>
    </div>
  </div>
</div>

// carr/src/components/Purchase.tsx
import { useState } from 'react';
import { X, Check, Loader2 } from 'lucide-react';

interface PurchaseModalProps {
  isOpen: boolean;
  onClose: () => void;
  // Añadimos props para que el componente sea dinámico según el vehículo
  vehicleData?: {
    price: number;
    model: string;
    year?: number;
    color: string;
  };
}

interface FormData {
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  reference_number: string;
  paymentMethod: string;
  notes: string;
}

const emptyForm: FormData = {
  first_name: '',
  last_name: '',
  email: '',
  phone: '',
  reference_number: '',
  paymentMethod: 'Transferencia', // Valor por defecto
  notes: '',
};

export default function Purchase({ isOpen, onClose, vehicleData }: PurchaseModalProps) {
  const [formData, setFormData] = useState<FormData>(emptyForm);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  // El precio y modelo vienen del componente padre o se fijan aquí
  const currentVehicle = vehicleData || {
    price: 50000.00,
    model: "RELY",
    year: 2024,
    color: "Blanco"
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    setError('');
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError('');

    // Validaciones básicas de cliente
    if (!formData.first_name || !formData.last_name || !formData.email || !formData.phone || !formData.reference_number) {
      setError('Por favor completa todos los campos obligatorios');
      return;
    }

    setIsLoading(true);

    // Mapeo de datos para que coincidan con OrdenVentaCreateSerializer en Django
    const dataToSend = {
      first_name: formData.first_name,
      last_name: formData.last_name,
      email: formData.email,
      phone: formData.phone,
      reference_number: formData.reference_number,
      price: currentVehicle.price,
      vehicleModel: currentVehicle.model,
      vehicleYear: currentVehicle.year,
      vehicleColor: currentVehicle.color,
      paymentMethod: formData.paymentMethod,
      notes: formData.notes
    };

    try {
      // Reemplaza con tu URL real de producción o desarrollo
      const response = await fetch('http://localhost:8000/api/ordenes/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          // Importante: Si usas IsAuthenticated, necesitas enviar el token
          'Authorization': `Bearer ${localStorage.getItem('access_token')}` 
        },
        body: JSON.stringify(dataToSend)
      });

      const result = await response.json();

      if (response.ok) {
        setIsSubmitted(true);
        setTimeout(() => {
          onClose();
          setFormData(emptyForm);
          setIsSubmitted(false);
        }, 4000);
      } else {
        // Manejo de errores específicos del Serializer (ej. referencia duplicada)
        if (result.reference_number) {
          setError(`Error: ${result.reference_number[0]}`);
        } else if (result.detail) {
          setError("No tienes permiso o tu sesión expiró.");
        } else {
          setError("Hubo un problema al procesar la orden.");
        }
      }
    } catch (err) {
      setError("No se pudo conectar con el servidor de ventas.");
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4 overflow-y-auto">
      <div className="bg-gray-950 rounded-2xl w-full max-w-md shadow-2xl border border-gray-800 my-8">
        <div className="flex justify-between items-center p-6 border-b border-gray-800">
          <h2 className="text-2xl font-bold text-white">Finalizar Compra</h2>
          <button onClick={onClose} className="p-2 hover:bg-gray-800 rounded-lg transition-colors">
            <X className="text-gray-400" size={24} />
          </button>
        </div>

        <div className="p-6">
          {isSubmitted ? (
            <div className="text-center py-8">
              <div className="flex justify-center mb-4">
                <div className="bg-green-500/20 p-4 rounded-full">
                  <Check className="text-green-500" size={40} />
                </div>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">¡Orden Guardada!</h3>
              <p className="text-gray-400 mb-4">La referencia {formData.reference_number} ha sido registrada en el sistema.</p>
              <p className="text-orange-500 text-sm font-medium">Cerrando ventana...</p>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4">
              {/* Resumen del Vehículo */}
              <div className="bg-gray-900 p-4 rounded-lg border border-gray-800 mb-4">
                <div className="flex justify-between items-end">
                  <div>
                    <p className="text-gray-400 text-xs uppercase tracking-wider">Vehículo</p>
                    <p className="text-xl font-bold text-white">{currentVehicle.model} <span className="text-gray-500 text-sm">{currentVehicle.year}</span></p>
                  </div>
                  <div className="text-right">
                    <p className="text-gray-400 text-xs uppercase tracking-wider">Precio</p>
                    <p className="text-2xl font-bold text-orange-500">${currentVehicle.price.toLocaleString()}</p>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-gray-400 mb-1 uppercase">Nombres</label>
                  <input type="text" name="first_name" value={formData.first_name} onChange={handleInputChange} required
                    className="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-400 mb-1 uppercase">Apellidos</label>
                  <input type="text" name="last_name" value={formData.last_name} onChange={handleInputChange} required
                    className="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1 uppercase">Email</label>
                <input type="email" name="email" value={formData.email} onChange={handleInputChange} required
                  className="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1 uppercase">Teléfono</label>
                <input type="tel" name="phone" value={formData.phone} onChange={handleInputChange} required
                  className="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-gray-400 mb-1 uppercase">Ref. de Pago</label>
                  <input type="text" name="reference_number" value={formData.reference_number} onChange={handleInputChange} required
                    className="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-400 mb-1 uppercase">Método</label>
                  <select name="paymentMethod" value={formData.paymentMethod} onChange={handleInputChange}
                    className="w-full px-4 py-2 bg-gray-900 border border-gray-700 rounded-lg text-white focus:border-orange-500 outline-none">
                    <option value="Transferencia">Transferencia</option>
                    <option value="Zelle">Zelle</option>
                    <option value="Efectivo">Efectivo</option>
                    <option value="Crypto">Crypto</option>
                  </select>
                </div>
              </div>

              {error && (
                <div className="bg-red-500/10 border border-red-500/50 text-red-400 p-3 rounded-lg text-xs italic">
                  ⚠️ {error}
                </div>
              )}

              <div className="pt-4 space-y-3">
                <button type="submit" disabled={isLoading}
                  className="w-full bg-orange-600 text-white py-3 rounded-lg font-bold hover:bg-orange-700 transition-all disabled:opacity-50 flex justify-center items-center gap-2">
                  {isLoading ? (
                    <>
                      <Loader2 className="animate-spin" size={20} />
                      Procesando con el Servidor...
                    </>
                  ) : 'Confirmar y Registrar Venta'}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}
